using MetricForestCompletion
using Random
using Clustering

function run_gaussian_test()
    # Setup Params
    PrecisionType = Float64
    
    dim = 4
    num_gauss = 100
    points_per_gauss = 200
    clusters = 16 
    
    # Distance Metric
    dist_func = euclidean 

    # Generate Dataset
    points, ground_truth = generate_gaussians(
        PrecisionType; 
        dim = dim, 
        num_centers = num_gauss, 
        points_per_center = points_per_gauss,
        mean_range = (PrecisionType(-5.0), PrecisionType(5.0)),
        sigma_range = (PrecisionType(0.5), PrecisionType(0.8))
    )

    # Initial Clustering
    clustering_result = k_centering(points, clusters, dist_func)

    # MFC 
    mfc_result = metric_forest_completion(
        points, 
        clusters, 
        clustering_result.assignments,
        dist_func
    )

    println("MFC Test Results")
    println("Data Type:           ", eltype(eltype(points)))
    println("Points Generated:    ", length(points))
    println("Clustering Runtime:  ", clustering_result.runtime, " seconds")
    println("MFC Total Runtime:   ", mfc_result.completion_runtime, " seconds")
    println("Cluster Edges Found: ", length(mfc_result.cluster_edges))

    # Combine all edges generated by MFC to form the complete spanning forest/tree
    all_ST_edges = vcat(mfc_result.cluster_edges, mfc_result.completion_edges)
    num_points = length(points)

    # Using a distance threshold
    threshold = 1.5 # Maybe use some heuristic here
                    # Perahps also try all threshold values, and return the one that is clostest to ground truth clustering
    threshold_result = single_linkage_threshold(all_ST_edges, num_points, threshold)
    
    println("Unique Clusters:    ", length(unique(threshold_result.assignments)))

    # Another option; Target k clusters
    # target_k = clusters
    # k_result = single_linkage_k_clusters(all_ST_edges, num_points, target_k)

    ### Evaluation ###
    println("Initial K-Centering:")
    kc_ari = randindex(clustering_result.assignments, ground_truth)[1]
    kc_nmi = mutualinfo(clustering_result.assignments, ground_truth, normed=true)
    println("ARI:", round(kc_ari, digits=4))
    println("NMI:", round(kc_nmi, digits=4))

    println("\nMFC Single Linkage (Threshold):")
    mfc_ari = randindex(threshold_result.assignments, ground_truth)[1]
    mfc_nmi = mutualinfo(threshold_result.assignments, ground_truth, normed=true)
    println("ARI:", round(mfc_ari, digits=4))
    println("NMI:", round(mfc_nmi, digits=4))

end

run_gaussian_test()