using MetricForestCompletion
using Random
using Clustering


function run_gaussian_test()
    # Setup Params
    PrecisionType = Float64
    
    dim = 8
    num_gauss = 16
    num_points = 20000
    num_clusters = 16 
    
    # Distance Metric
    dist_func = euclidean 

    # Generate Dataset
    points, ground_truth = generate_gaussians(
        PrecisionType; 
        dim = dim, 
        num_centers = num_gauss, 
        points_per_center = num_points ÷ num_gauss,
        mean_range = (PrecisionType(-5), PrecisionType(5)),
        sigma_range = (PrecisionType(0.5), PrecisionType(0.8))
    )

    # Initial Clustering
    clustering_result = k_centering(points, num_clusters, 1, dist_func)

    # MFC Variants
    mfc_approx_result = metric_forest_completion_approx(
        points, num_clusters, clustering_result.assignments, dist_func
    )

    mfc_optimal_result = metric_forest_completion_optimal(
        points, num_clusters, clustering_result.assignments, dist_func
    )

    mfc_simple_result = metric_forest_completion_simple(
        points, num_clusters, clustering_result.assignments, dist_func
    )

    # Combine all edges generated by MFC to form the complete spanning forest/tree
    all_ST_approx_edges  = vcat(mfc_approx_result.cluster_edges, mfc_approx_result.completion_edges)
    all_ST_optimal_edges = vcat(mfc_optimal_result.cluster_edges, mfc_optimal_result.completion_edges)
    all_ST_simple_edges  = vcat(mfc_simple_result.cluster_edges, mfc_simple_result.completion_edges)
    

    # Calculate Baseline and Threshold to Create Clusters from Spanning Trees
    num_points = length(points) 

    threshold = 1.5
    target_k = num_clusters

    # Compute Optimal MST
    t_mst_compute = @elapsed mst_edges = mst_implicit(points, dist_func)
    mst_complete = convert_mst_to_weight(mst_edges)
    # mst_result = single_linkage_threshold(mst_complete, num_points, threshold)

    # Compute Naive ST
    naive_st_edges = naive_random_st(points, dist_func)
    naive_st_complete = convert_mst_to_weight(naive_st_edges)
    # naive_st_result = single_linkage_threshold(naive_st_complete, num_points, threshold)

    # Standard thresholding on Approx MFC
    # threshold_result_approx = single_linkage_threshold(all_ST_approx_edges, num_points, threshold)
    # k_result_approx = single_linkage_k_clusters(all_ST_approx_edges, num_points, target_k)

    # Parameter sweeps for best thresholds
    t_sweep_mst = @elapsed best_result_mst, max_ari_mst = best_single_linkage_threshold(mst_complete, num_points, ground_truth )
    t_sweep_naive = @elapsed best_result_naive, max_ari_naive = best_single_linkage_threshold(naive_st_complete, num_points, ground_truth )

    t_sweep_approx = @elapsed best_result_approx, max_ari_approx = best_single_linkage_threshold(all_ST_approx_edges, num_points, ground_truth )
    t_sweep_optimal = @elapsed best_result_optimal, max_ari_optimal = best_single_linkage_threshold(all_ST_optimal_edges, num_points, ground_truth )
    t_sweep_simple = @elapsed best_result_simple, max_ari_simple = best_single_linkage_threshold(all_ST_simple_edges, num_points, ground_truth )

    # Dispaly Results
    println("MFC Test Results")
    println("Data Type:           ", eltype(eltype(points)))
    println("Points Generated:    ", floor(num_points ÷ num_gauss) * num_gauss)
    println("Cluster Edges Found: ", length(mfc_approx_result.cluster_edges))

    println("Optimal MST Computation:             ", round(t_mst_compute, digits=4), " seconds")

    println("\n### MFC Runtimes ###")
    println("Initial Clustering:                  ", round(clustering_result.runtime, digits=4), " seconds")
    
    println("\nMFC Approx Sub-cluster Runtime:      ", round(mfc_approx_result.sub_cluster_runtime, digits=4), " seconds")
    println("MFC Approx Completion Edges Runtime: ", round(mfc_approx_result.completion_edges_runtime, digits=4), " seconds")
    println("MFC Approx Total Runtime:            ", round(mfc_approx_result.completion_runtime, digits=4), " seconds")

    println("\nMFC Optimal Sub-cluster Runtime:     ", round(mfc_optimal_result.sub_cluster_runtime, digits=4), " seconds")
    println("MFC Optimal Completion Edges Runtime:", round(mfc_optimal_result.completion_edges_runtime, digits=4), " seconds")
    println("MFC Optimal Total Runtime:           ", round(mfc_optimal_result.completion_runtime, digits=4), " seconds")

    println("\nMFC Simple Sub-cluster Runtime:      ", round(mfc_simple_result.sub_cluster_runtime, digits=4), " seconds")
    println("MFC Simple Completion Edges Runtime: ", round(mfc_simple_result.completion_edges_runtime, digits=4), " seconds")
    println("MFC Simple Total Runtime:            ", round(mfc_simple_result.completion_runtime, digits=4), " seconds")

    println("\n### Parameter Sweep Runtimes ###")
    println("MST Sweep Time:                      ", round(t_sweep_mst, digits=4), " seconds")
    println("Naive ST Sweep Time:                 ", round(t_sweep_naive, digits=4), " seconds")
    println("MFC Approx Sweep Time:               ", round(t_sweep_approx, digits=4), " seconds")
    println("MFC Optimal Sweep Time:              ", round(t_sweep_optimal, digits=4), " seconds")
    println("MFC Simple Sweep Time:               ", round(t_sweep_simple, digits=4), " seconds")

    println("\n### Evaluation ###")
    
    println("\nInitial K-Centering:")
    kc_ari = randindex(clustering_result.assignments, ground_truth)[1]
    kc_nmi = mutualinfo(clustering_result.assignments, ground_truth, normed=true)
    println("ARI: ", round(kc_ari, digits=4))
    println("NMI: ", round(kc_nmi, digits=4))

    println("\nMST Single Linkage (Best Threshold):")
    mst_nmi = mutualinfo(best_result_mst.assignments, ground_truth, normed=true)
    println("ARI: ", round(max_ari_mst, digits=4))
    println("NMI: ", round(mst_nmi, digits=4))

    println("\nNaive ST Single Linkage (Best Threshold):")
    naive_nmi = mutualinfo(best_result_naive.assignments, ground_truth, normed=true)
    println("ARI: ", round(max_ari_naive, digits=4))
    println("NMI: ", round(naive_nmi, digits=4))

    println("\nMFC Approx Single Linkage (Best Threshold):")
    mfc_best_approx_nmi = mutualinfo(best_result_approx.assignments, ground_truth, normed=true)
    println("ARI: ", round(max_ari_approx, digits=4))
    println("NMI: ", round(mfc_best_approx_nmi, digits=4))

    println("\nMFC Optimal Single Linkage (Best Threshold):")
    mfc_best_optimal_nmi = mutualinfo(best_result_optimal.assignments, ground_truth, normed=true)
    println("ARI: ", round(max_ari_optimal, digits=4))
    println("NMI: ", round(mfc_best_optimal_nmi, digits=4))

    println("\nMFC Simple Single Linkage (Best Threshold):")
    mfc_best_simple_nmi = mutualinfo(best_result_simple.assignments, ground_truth, normed=true)
    println("ARI: ", round(max_ari_simple, digits=4))
    println("NMI: ", round(mfc_best_simple_nmi, digits=4))

end

run_gaussian_test()